# config.yaml
data:
  train_dir: "data/processed/kaggle_sp500/out/train"
  test_dir: "data/processed/kaggle_sp500/out/test"
  batch_size: 128
  segment_length: 30
  segment_step: 5
  label_column: "close"
training:
  num_epochs: 200
experiment:
  tags: []
