# config.yaml
models:
  encoder:
    input_size: null # determine by the data shape
    hidden_size: 128
    output_size: 128
    num_layers: 1
  projector:
    input_size: 128 # encoder output size
    hidden_layers:
      - [64, "relu"]
      - [32, "relu"]
    output_size: 16
  probe:
    input_size: 128 # encoder output size
    hidden_layers:
      - [64, "relu"]
      - [32, "relu"]
    output_size: 1
optimizers:
  simclr_lr: 1.0e-6
  finetuning_lr: 1.0e-3
  baseline_lr: 1.0e-3
training:
  temperature: 0.5
experiment:
  name: "simple-lstm"
  tags: ["lstm", "simclr"]
